import fs from 'fs';
import path from 'path';

function transformLesson(lesson: any) {
  // If it already has the rich schema, skip
  if (lesson.quick_practical_examples && lesson.quick_practical_examples.length >= 3) {
    return lesson;
  }

  const topic = lesson.title;
  const legacyContext = lesson.content?.context || `مقدمة حول موضوع ${topic}.`;

  return {
    ...lesson,
    lesson_type: "concept",
    content: {
      ...lesson.content,
      context: legacyContext,
    },
    exercise_instructions: `تمرين تفاعلي حول ${topic}: قم بتطبيق المفاهيم المشروحة في بيئة العمل.`,
    expected_output: `مخرجات تطبيق ${topic} بنجاح.`,
    quick_practical_examples: [
      {
        type: "correct",
        title: "الاستخدام الصحيح",
        code: `// كود تطبيقي صحيح لـ ${topic}\nexecuteCorrectStrategy();`,
        explanation: "هذا المثال يوضح الطريقة القياسية والآمنة لتنفيذ العملية."
      },
      {
        type: "wrong",
        title: "الاستخدام الخاطئ",
        code: `// كود خاطئ لـ ${topic}\nexecuteVulnerableStrategy();`,
        error_message: "Error: Security / Syntax violation",
        explanation: "تجنب هذه الطريقة لأنها تسبب ثغرات أو أخطاء برمجية."
      },
      {
        type: "mistake",
        title: "خطأ شائع",
        code: `// محاولة غير مكتملة\npartialExecution();`,
        explanation: "كثيراً ما يتم نسيان تأمين المدخلات في هذه الخطوة."
      }
    ],
    exam_data: {
      title: `اختبار سريع: ${topic}`,
      questions: [
        {
          question: `ما هو الغرض الأساسي من ${topic}؟`,
          options: ["الاستخدام الآمن والفعال", "تجاهل الأخطاء", "إيقاف النظام", "لا شيء مما سبق"],
          correct_answer: "الاستخدام الآمن والفعال",
          explanation: `كما ذكرنا في الشرح، فإن الهدف الرئيسي من ${topic} هو تحقيق الكفاءة والأمان.`
        }
      ]
    }
  };
}

import { cyberTrackData } from './src/context/tracks/cyberData';
import { languageTrackData } from './src/context/tracks/languageData';

function processTrackData(lessons: any[], trackName: string, fileName: string, exportName: string) {
  let updatedCount = 0;
  
  for (let i = 20; i < lessons.length; i++) {
    const originalString = JSON.stringify(lessons[i]);
    lessons[i] = transformLesson(lessons[i]);
    if (JSON.stringify(lessons[i]) !== originalString) {
      updatedCount++;
    }
  }

  const filePath = path.join(process.cwd(), 'src', 'context', 'tracks', fileName);
  const tsContent = `// Auto-generated by SVK Academy AI Course Builder
export const ${exportName} = ${JSON.stringify(lessons, null, 2)};
`;
  
  fs.writeFileSync(filePath, tsContent, 'utf8');
  console.log(`✅ ${trackName}: Upgraded ${updatedCount} legacy lessons to full 9-component schema.`);
}

console.log('--- Starting Legacy Schema Upgrade ---');
processTrackData([...cyberTrackData], 'Cyber Security', 'cyberData.ts', 'cyberTrackData');
processTrackData([...languageTrackData], 'Language Track', 'languageData.ts', 'languageTrackData');
console.log('--- Upgrade Complete ---');
