import { NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';

export async function POST(request: Request) {
  try {
    const { slug, lessons } = await request.json();

    if (!slug || !lessons || !Array.isArray(lessons)) {
      return NextResponse.json({ error: 'Invalid payload. slug and lessons array are required.' }, { status: 400 });
    }

    // Security check for filename to prevent directory traversal
    if (!/^[a-zA-Z0-9-]+$/.test(slug)) {
      return NextResponse.json({ error: 'Invalid slug format.' }, { status: 400 });
    }

    const fileName = `${slug}Data.ts`;
    const tracksDir = path.join(process.cwd(), 'src', 'context', 'tracks');
    const filePath = path.join(tracksDir, fileName);

    // Generate TypeScript content
    const tsContent = `// Auto-generated by SVK Academy AI Course Builder
export const ${slug}TrackData = ${JSON.stringify(lessons, null, 2)};
`;

    // Ensure directory exists
    if (!fs.existsSync(tracksDir)) {
      fs.mkdirSync(tracksDir, { recursive: true });
    }

    // Write file
    fs.writeFileSync(filePath, tsContent, 'utf8');

    return NextResponse.json({ success: true, message: `Successfully published ${lessons.length} lessons to ${fileName}` });
  } catch (error: any) {
    console.error('Publish API Error:', error);
    return NextResponse.json({ error: error.message || 'Internal Server Error during publishing' }, { status: 500 });
  }
}
